### ISSUE TITLE
Issue with editing single field

### ISSUE THREAD

**Issue by j-simpson1** [timfarkas/Serenify#69]
Hi Tim,

Hope you're well and having a great evening.

Just having a sight issue trying to edit a single field.

Apologies if I'm missing something obvious or if it's been fixed in the latest patch. Happy to discuss over a call.

Many thanks,

James

Test code:

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database.database import Database

db = Database()

userRelation = db.getRelation('User').editFieldInRow(2, targetAttribute='email', value='john.doe@newdomain.com')

db.close()

Error:

jamessimpson@eduroam-int-dhcp-97-94-246 Serenify % /usr/local/bin/python3 "/Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science 
MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/admin/Test.py"
2024-11-26 16:40:11,658 - INFO - Initializing database...
2024-11-26 16:40:11,658 - INFO - Found database file /Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/database.pkl, loading from file...
2024-11-26 16:40:11,658 - INFO - Loading DB from /Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/database.pkl
2024-11-26 16:40:11,659 - INFO - Success loading database
2024-11-26 16:40:11,659 - INFO - Successfully initialized database.
Traceback (most recent call last):
  File "/Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/admin/Test.py", line 10, in <module>
    userRelation = db.getRelation('User').editFieldInRow(2, targetAttribute='email', value='john.doe@newdomain.com')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/database/dataStructs.py", line 553, in editFieldInRow
    self._validateRowValues(attributeList=row.values, entityType=row.values[self.__typeIndex-o])
  File "/Users/jamessimpson/Library/Mobile Documents/com~apple~CloudDocs/Documents/Computer Science MSc/COMP0066 Introductory Programming/Project/Untitled/Serenify/database/dataStructs.py", line 652, in _validateRowValues
    raise TypeError(f"Validation is switched on, but class of name {entityType} could not be found among {relevantClasses}")
TypeError: Validation is switched on, but class of name Doe could not be found among [<class 'database.entities.Patient'>, <class 'database.entities.Admin'>, <class 'database.entities.MHWP'>]
jamessimpson@eduroam-int-dhcp-97-94-246 Serenify %

**Comment by timfarkas** [comment]
did you make sure that you're on the latest version of the database folder?

**Comment by timfarkas** [comment]
(which is still in dbFixes)
