### ISSUE TITLE
BUG: patientMain bugs when opened via main.py

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#85]
When I submit any mood score, with or without comment, it does nothing and throws this error.

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 189, in submit_mood
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 594, in get
    return int(self._tk.getdouble(value))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: expected floating-point number but got ""
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 592, in get
    return self._tk.getint(value)
           ^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: expected integer but got ""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 189, in submit_mood
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 594, in get
    return int(self._tk.getdouble(value))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: expected floating-point number but got ""

**Comment by timfarkas** [comment]
nevermind, seems to be due to a pandas import error my end

**Comment by timfarkas** [comment]
nevermind, this always seems to happen when opening patientMain via main.py (rather than opening it directly)

**Comment by timfarkas** [comment]
also, when saving a journal entry it throws: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 250, in save_journal_entry
NameError: name 'JournalEntry' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 250, in save_journal_entry
NameError: name 'JournalEntry' is not defined

**Comment by bielasekk** [comment]
It only throws an error for both mood and journal submission when submitted right after logging in. If I for example go to edit personal info first and then go back and submit mood it works all good. So it must be related to the flow somehow and moving from main to login to patient

**Comment by timfarkas** [comment]
seems to have been fixed, awesome!
