### ISSUE TITLE
BUG: Journal Entry submission throws error

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#86]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 250, in save_journal_entry
NameError: name 'JournalEntry' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<string>", line 250, in save_journal_entry
NameError: name 'JournalEntry' is not defined

**Comment by timfarkas** [comment]
nevermind, seems to be due to a pandas import issue on my end
